version: '3.7'
services:
    postgres:
        image: postgres:12.7
        container_name: db_delitos
        #restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432' #'5438:5432'
        volumes:
          - ./sql/delitos.sql:/datasql/crearTablas.sql
          #esto no esta operativo
          #- ./scriptsBash/entrypoint.sh:/init.sh
          - ./scriptsBash/entrypoint.sh:/docker-entrypoint-initdb.d/entrada.sh
        #command: ['sh', '/init.sh']
networks:
  default:
    name: network_app
